on: [push]

jobs:
  pdf_to_html:
    runs-on: ubuntu-latest
    name: A job to convert pdf to html
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Convert PDF to HTML
        id: hello
        uses: mohsenasm/pdf2htmlEX-github-action@main
        with:
          zoom: '1.3'
          filename: 'resume.pdf'
